name: Netlify CI
runs-on: ubuntu-latest
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1.4.3
        with:
          node-version: '12'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Get caches
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            vendor
          key: ${{ runner.os }}-build-caches

      - name: Install node dependencies
        run: yarn install

      - name: Install PHP dependencies
        run: composer install

      - name: Build site with production mode
        run: yarn run production

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build_production
          path: build_production
